supergoodsystems/supergood-py

- setup.py
pytest_httpserver v1.0.6 is incompatible with werkzeug 2.3+. Either had to peg werkzeug back or bump pytest_httpserver
> Bump pytest_httpserver version to 1.0.8

- setup.py
- src/supergood/client.py
This PR includes the library and library version in the header of requests being made to supergood. These are consumed on supergood's side and used for debugging.
> Add library info to supergood-bound headers

- README.md
- publish.sh
- setup.cfg
- setup.py
publish script updates readme.md and version info. Will become part of github hook soon, but manual for now
> Changes from 1.1.0 publish

- src/supergood/client.py
- src/supergood/constants.py
- tests/helper.py
- tests/test_dont_log.py
Adds new parameters to the base (local) config. These parameters are, with defaults,
```python
"logRequestHeaders": True, 
"logRequestBody": True, 
"logResponseHeaders": True,
"logResponseBody": True,
```
Setting any of them to False will null out the value being sent to Supergood. While this limits SG's ability to do anomaly detection, we think it's a useful feature to allow users to be even more in control of their own data.
> add log{Request|Response}{Body|Headers} config params

- src/supergood/client.py
- src/supergood/helpers.py
tries to decode everything that should be a string type
> make all the things strings

- src/supergood/client.py
- src/supergood/constants.py
- src/supergood/helpers.py
- tests/helper.py
New feature: redact by default.
When first installing supergood, it will, by default, not send payload values back to Supergood. It will send key metadata (path, type, size) back only. To send payload values back, you now have to set
`forceRedactAll: False`
Tested locally using simple and nested array responses
> redact by default

- src/supergood/client.py
Python's `datetime.toisoformat()` function doesn't actually include time zone information on it, nor does it include a `Z` for Zulu in UTC times. while we could send timezone aware datetimes back to supergood, we might as well convert the date to UTC and then send a timezone aware string using Zulu back to Supergood
> Send datetime-aware strings back to supergood

- src/supergood/constants.py
see title. Can still be set to true manually, and will still override other flags.
> set forceRedactAll to false by default

- src/supergood/helpers.py
redact by default does successfully redact by default, but breaks some upstream supergood functionalities because of a bug in nesting the sensitiveKeys within the metadata blob.
This PR nests the skeys correctly
> fix skey nesting for redact by default

- src/supergood/client.py
- tests/caching/test_location_request_body.py
- tests/caching/test_location_request_headers.py
- tests/helper.py
During testing we'd overlooked test cases involving a `location` value of `requestHeaders/requestBody`. In some cases requestHeaders were not json serializable and we were seeing endpoint matching fail.
This PR fixes the unserializable headers by calling `dict()` on them, which seems to make them serializable.
It also adds 2 new test cases to ensure a location of `requestHeaders` and `requestBody` are successfully caught, as these two are weirder than matching to other locations because they involve a json dump
> Fix request headers unserializable

- src/supergood/client.py
Adds microsecond to the datetime string that gets sent back to supergood. While SG only considers down to millisecond level precision for now, it can still consume and round it to the nearest millisecond, so might as well future-proof.
Tested by throwing events like this at SG and confirmed they are ingested properly
> support millisecond precision

- src/supergood/api.py
- src/supergood/client.py
- src/supergood/constants.py
report errors to the telemetry endpoint. We're separating out error reporting from event reporting for the purposes of flow control.
> Set telemetry endpoint

- setup.py
- src/supergood/vendors/urllib3.py
the base `http.client.HTTPConnection` is not used by urllib3 v2, hence why it's a breaking change for this library. Instead we hook into it's `request` method on the urllib3 HTTPConnection. The response is captured while reading the returned HTTPResponse object, which is patched in http.py
There's a chance we could patch even lower down in the base `http` lib code that gets invoked here, but that would require a reasonable rewrite. From my investigation that would require
- patching HTTPConnection.{`putresponse` and `putheaders`} to make sure the url, method, and all of the headers are stored on the http connection in some supergood key/keys
- patching `HTTPConnection.send` to  build up the `data` fields into the entire request body, which requires building it up iteratively while waiting …
> Support urllib3 v2

- src/supergood/vendors/httpx.py
This is kinda the basis for why supporting capturing streamed responses is difficult with httpx
If the response is not being streamed, it always gets read, so there's an obvious spot for the patch. For streamed responses the same isn't true. It seems like some of the benefit of streaming is deciding how much to read into memory at any given time, so the raw response object is returned. An end user could call `.read()` on that object (and our current implementation would cache it) but there are other entry points to reading the data within, one of which is to iter over it.
While we could call `.read()` ourselves on that response object and cache it, it's not clear to me we want to do that, as it seems to break one of the fundamental "purposes" of streaming a response. What seems more …
> support httpx streaming

- .github/workflows/test.yml
Need to add the staging-telemetry URL or it'll default to the prod URL and you'll get an unauthorized alert.
> Fixing github actions

- src/supergood/api.py
- src/supergood/client.py
- src/supergood/constants.py
- tests/conftest.py
We're moving the error logs to a new telemetry endpoint, along with an additional telemetry print during flush to assist us in debugging remotely.
> Add telemetry endpoint

- src/supergood/client.py
The way celery forks the existing main process ends up being problematic for the supergood python client.
It makes a copy of all the in-memory items on the client, but does NOT copy over the threads running on the main thread. This means remote configs will not get updated in the background, and flushes won't occur in the background. There's a few ways we're thinking of addressing this.
In the short term:
This PR ensures that the forked celery worker will still report events to supergood. The downside is we can't make use of batching like we can in the main thread, but it was a quick option to ensure we don't miss events.
In the medium term:
we're thinking about utilizing disk writes on forked threads so we can bundle those up on either the main thread or in a sidecar agent. This will …
> Add ability to flush during response cache for celery

- setup.py
- src/supergood/client.py
- src/supergood/vendors/urllib3.py
After some consideration, while in general libraries should be moving toward urllib3 v2 support, for a library like ours it makes more sense to be inclusive where possible.
This PR undoes the decision to peg urllib3 to v2+, instead opting to go with whatever is decided from other dependencies. If it's urllib3 v1, the patch we need for v2 simply won't be applied.
This also takes a few other tweaks to telemetry out. One is to report the _number_ of keys instead of their uuids, and the other is a future proofing to not death loop if we decide to point telemetry at a different hostname in the future.
> Support all versions of urllib3 and a few telemetry fixes

- setup.cfg
- setup.py
- src/supergood/client.py
- src/supergood/constants.py
When running in a serverless environment, there's a few things we want to keep in mind
1. long-running daemon threads are a bad idea given the ephemeral nature of the serverless environment
2. For a lambda-esque setup where the serverless run is quick and thin, expensive initialization calls are also a bad idea
So to enable running in a serverless environment, this PR adds 2 new features
- a `useRemoteConfig` flag that defaults to `True`. By setting this to `False`, the client will not request a remote config from supergood. This solves (2) above
- a `runThreads` flag that defaults to `True`. By setting this to `False`, we will not spin up threads to pull the remote config intermittently or to flush intermittently. Flushing will have to be done manually instead. This solves (1) above …
> Add config flags to enable serverless supergood

- .github/workflows/test.yml
- src/supergood/client.py
- src/supergood/helpers.py
- src/supergood/vendors/helpers.py
- src/supergood/vendors/httpx.py
- tests/vendors/test_httpx.py
OpenAI uses the HTTPX iter_bytes function to iterate through a response. We currently weren't patching that, so responses were getting dropped.
During the investigation we also had to make some decisions on how to represent streamed responses internally in such a way that we can correctly ingest the keys on the Supergood server side. This work is still ongoing.
Tests TODO
> fix openai streaming

- pyproject.toml
- src/supergood/helpers.py
- tests/redaction/test_redact_by_default.py
Currently when in redact-by-default mode, we don't properly allow keys that contain an array indexer in them (e.g. [1]). This PR fixes that
Tested locally, and added a unit test
> Fix allowed keys for array-type keys

- .gitignore
- src/supergood/__init__.py
- src/supergood/client.py
- tests/conftest.py
- tests/test_core.py
This is a BREAKING CHANGE due to it changing the way clients should be initialized.
However the main purpose of the PR is to introduce a new feature to the python client: Tagging!
The breaking change allows the module-level client to be imported in any file, and for http calls to be tagged with metadata. This will allow more granular slicing of data in views within the Supergood dashboard, as well as more granular tag-level alerting. This can be achieved like so (assuming the Client was initialized earlier in another file):
```
from supergood import Client as supergood_client
with supergood_client.tagging({'feature': 'A', 'customer': 'B'}):
requests.get(<url>)
```
Change has been tested locally using a very-multithreaded setup. 2 new tests have been added. This will be released as part of …
> [BREAKING CHANGE] Feature: Tagging

- src/supergood/client.py
- src/supergood/helpers.py
- src/supergood/remote_config.py
- tests/caching/test_method.py
- tests/helper.py
- tests/test_remote_config.py
Currently supergood endpoints are categorized using a regex pattern matched against a few options. However, for an endpoint that is queried using multiple methods (GET, POST, PATCH, etc) all these calls get conflated to the same endpoint.
There are some cases where this may be desired, but in general a POST and a GET to an endpoint should not be considered the same. This PR will now allow for an endpoint's method to be specified in the remote config. Calls must match both the regex and the endpoint method now to be considered a match.
Added unit test case, currently testing locally.
> Feature: Endpoint Categorization including method
